import {
  Activity,
  Apple,
  Baby,
  Bell,
  BookOpen,
  Brain,
  Building2,
  CalendarDays,
  ChefHat,
  ClipboardCheck,
  Columns3,
  Database,
  Droplets,
  Dumbbell,
  FileCog,
  FileText,
  FlaskConical,
  Gauge,
  LayoutDashboard,
  MessageSquare,
  PieChart,
  Ruler,
  Settings,
  ShieldAlert,
  Stethoscope,
  Syringe,
  Trophy,
  Users,
  type LucideIcon,
} from "lucide-react";

export const MODULE_AREAS = [
  "operational-center",
  "clinical",
  "laboratory",
  "nutrition",
  "hospital",
  "pediatric",
  "sports",
  "administration",
  "reports",
  "system",
] as const;

export type ModuleArea = (typeof MODULE_AREAS)[number];
export type ModuleStatus = "active" | "partial" | "coming_soon" | "blocked";
export type ModuleContext = "tenant" | "patient" | "pack" | "admin" | "system";

export type ModuleDefinition = {
  id: string;
  label: string;
  description: string;
  area: ModuleArea;
  route?: string;
  icon: LucideIcon;
  permission?: string;
  pack?: string;
  status: ModuleStatus;
  priority: number;
  isClinical: boolean;
  isAdmin: boolean;
  isExperimental: boolean;
  requiresTenant: boolean;
  requiresPatient: boolean;
  comingSoon: boolean;
  enabledByDefault: boolean;
  allowedContexts: ModuleContext[];
  showInSidebar?: boolean;
  blockedReason?: string;
  pending?: string;
};

export const MODULE_AREA_LABELS: Record<ModuleArea, string> = {
  "operational-center": "Centro operativo",
  clinical: "Clínica",
  laboratory: "Laboratorio",
  nutrition: "Nutrición",
  hospital: "Hospitalario",
  pediatric: "Pediatría",
  sports: "Deportivo",
  administration: "Administración",
  reports: "Reportes",
  system: "Sistema",
};

export const MODULE_REGISTRY: ModuleDefinition[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    description: "Panel ejecutivo del tenant activo.",
    area: "operational-center",
    route: "/app",
    icon: LayoutDashboard,
    status: "active",
    priority: 10,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant"],
    showInSidebar: true,
  },
  {
    id: "copilot",
    label: "Copilot clinico",
    description: "Centro contextual con reglas locales, tareas, timeline y enlaces internos. No es IA medica.",
    area: "operational-center",
    route: "/app/copilot",
    icon: Brain,
    permission: "ai.assist",
    status: "active",
    priority: 20,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    showInSidebar: true,
  },
  {
    id: "alerts",
    label: "Alertas",
    description: "Alertas y pendientes operativos visibles por tenant.",
    area: "operational-center",
    route: "/app/alerts",
    icon: Bell,
    permission: "alerts.read",
    status: "active",
    priority: 30,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    showInSidebar: true,
  },
  {
    id: "agenda",
    label: "Agenda",
    description: "Citas, seguimiento y calendario operativo.",
    area: "operational-center",
    route: "/app/agenda",
    icon: CalendarDays,
    permission: "appointments.read",
    status: "active",
    priority: 40,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    showInSidebar: true,
  },
  {
    id: "messages",
    label: "Mensajes",
    description: "Hilos y mensajes institucionales.",
    area: "operational-center",
    route: "/app/messages",
    icon: MessageSquare,
    permission: "messages.read",
    status: "active",
    priority: 50,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    showInSidebar: true,
  },
  {
    id: "patients",
    label: "Pacientes",
    description: "Listado clinico y acceso al expediente.",
    area: "clinical",
    route: "/app/patients",
    icon: Users,
    permission: "patients.read",
    status: "active",
    priority: 10,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    showInSidebar: true,
  },
  {
    id: "patient-detail",
    label: "Expediente",
    description: "Expediente longitudinal del paciente seleccionado.",
    area: "clinical",
    icon: BookOpen,
    permission: "patients.read",
    status: "active",
    priority: 20,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: true,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["patient"],
    pending: "Se abre desde un paciente real.",
  },
  {
    id: "evaluations",
    label: "Evaluaciones",
    description: "Evaluaciones clinicas y encuentros.",
    area: "clinical",
    route: "/app/encounters",
    icon: ClipboardCheck,
    permission: "encounters.manage",
    status: "active",
    priority: 30,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
  },
  {
    id: "plans",
    label: "Planes",
    description: "Planes nutricionales activos y seguimiento.",
    area: "clinical",
    route: "/app/plans",
    icon: FileText,
    permission: "nutrition_plans.approve",
    status: "active",
    priority: 40,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    showInSidebar: true,
  },
  {
    id: "anthropometry",
    label: "Antropometria",
    description: "Estacion antropometrica y medidas corporales.",
    area: "clinical",
    route: "/app/anthropometry",
    icon: Ruler,
    permission: "anthropometry.create",
    status: "active",
    priority: 50,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    showInSidebar: true,
  },
  {
    id: "screening",
    label: "Screening",
    description: "Tamizaje nutricional y riesgo.",
    area: "clinical",
    route: "/app/screening",
    icon: ShieldAlert,
    permission: "screening.create",
    status: "active",
    priority: 60,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    showInSidebar: true,
  },
  {
    id: "formulas",
    label: "Formulas",
    description: "Catalogo y parametros institucionales de formulas.",
    area: "clinical",
    route: "/app/formulas",
    icon: FlaskConical,
    permission: "settings.manage",
    status: "active",
    priority: 70,
    isClinical: true,
    isAdmin: true,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: false,
    allowedContexts: ["tenant", "admin"],
  },
  {
    id: "labs",
    label: "Labs",
    description: "Ordenes, resultados y tendencias de laboratorio.",
    area: "laboratory",
    route: "/app/labs",
    icon: FlaskConical,
    status: "active",
    priority: 10,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    showInSidebar: true,
  },
  {
    id: "lab-interpretations",
    label: "Interpretaciones",
    description: "Interpretaciones estructuradas de laboratorio.",
    area: "laboratory",
    icon: PieChart,
    status: "coming_soon",
    priority: 20,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: true,
    comingSoon: true,
    enabledByDefault: false,
    allowedContexts: ["patient"],
    pending: "Pendiente de reglas clinicas validadas.",
  },
  {
    id: "lab-report",
    label: "Reporte de laboratorios",
    description: "Reporte de laboratorios desde el centro de reportes.",
    area: "laboratory",
    icon: FileText,
    permission: "reports.export",
    status: "partial",
    priority: 30,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    pending: "Abrir desde Centro de reportes; report.exported pendiente de evidencia autenticada.",
  },
  {
    id: "foods",
    label: "Alimentos",
    description: "Biblioteca de alimentos y catalogos nutricionales.",
    area: "nutrition",
    route: "/app/foods",
    icon: Apple,
    permission: "foods.read",
    status: "active",
    priority: 10,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant"],
    showInSidebar: true,
  },
  {
    id: "recipes",
    label: "Recetas",
    description: "Constructor de recetas con calculo nutricional.",
    area: "nutrition",
    route: "/app/recipes",
    icon: ChefHat,
    permission: "recipes.read",
    status: "active",
    priority: 20,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant"],
    showInSidebar: true,
  },
  {
    id: "weekly-menu",
    label: "Menu semanal",
    description: "Matriz semanal de menu y porciones.",
    area: "nutrition",
    route: "/app/weekly-menu",
    icon: CalendarDays,
    permission: "weekly_menus.read",
    status: "active",
    priority: 30,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant"],
    showInSidebar: true,
  },
  {
    id: "nutrition-reports",
    label: "Reportes nutricionales",
    description: "Reportes de nutricion operativa desde reportes.",
    area: "nutrition",
    icon: FileText,
    permission: "reports.export",
    status: "partial",
    priority: 40,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant"],
    pending: "Abrir desde Centro de reportes; export audit pendiente de evidencia autenticada.",
  },
  {
    id: "enteral",
    label: "Enteral",
    description: "Cockpit enteral con planes, logs y tolerancia.",
    area: "hospital",
    route: "/app/pack/enteral/cockpit",
    icon: Droplets,
    pack: "enteral",
    status: "partial",
    priority: 10,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient", "pack"],
    showInSidebar: true,
    pending: "E2E autenticado pendiente por credenciales.",
  },
  {
    id: "parenteral",
    label: "Parenteral basico",
    description: "Soporte parenteral funcional basico controlado, no avanzado.",
    area: "hospital",
    route: "/app/pack/parenteral",
    icon: Syringe,
    pack: "parenteral",
    status: "partial",
    priority: 20,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient", "pack"],
    showInSidebar: true,
    pending: "No marcar como parenteral avanzado.",
  },
  {
    id: "hospital-support",
    label: "Soporte hospitalario",
    description: "Resumen de soporte enteral y parenteral desde expediente.",
    area: "hospital",
    icon: Stethoscope,
    status: "active",
    priority: 30,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: true,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["patient"],
    pending: "Se abre desde PatientDetail.",
  },
  {
    id: "tolerance-alerts",
    label: "Alertas de tolerancia",
    description: "Alertas derivadas de logs enterales reales.",
    area: "hospital",
    icon: ShieldAlert,
    permission: "alerts.read",
    status: "partial",
    priority: 40,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    pending: "Abrir desde Alertas; validacion E2E enteral pendiente.",
  },
  {
    id: "pediatric-curves",
    label: "Curvas pediatricas",
    description: "Curvas pediatricas con referencia incompleta controlada.",
    area: "pediatric",
    route: "/app/pediatric-curves",
    icon: Baby,
    permission: "pediatric_growth.read",
    pack: "pediatric",
    status: "partial",
    priority: 10,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient", "pack"],
    showInSidebar: true,
    pending: "CSV oficiales WHO/OMS faltantes.",
  },
  {
    id: "pediatric-controls",
    label: "Controles pediatricos",
    description: "Controles pediatricos vinculados al expediente.",
    area: "pediatric",
    icon: ClipboardCheck,
    permission: "pediatric_growth.read",
    status: "coming_soon",
    priority: 20,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: true,
    comingSoon: true,
    enabledByDefault: false,
    allowedContexts: ["patient"],
    pending: "Pendiente de flujo dedicado; actualmente se revisa en expediente/curvas.",
  },
  {
    id: "pediatric-reference-incomplete",
    label: "Referencia incompleta",
    description: "Estado seguro cuando faltan referencias oficiales.",
    area: "pediatric",
    route: "/app/pediatric-curves",
    icon: Database,
    permission: "pediatric_growth.read",
    status: "blocked",
    priority: 30,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    blockedReason: "Faltan CSV oficiales WHO/OMS.",
  },
  {
    id: "who-importer",
    label: "Importador WHO/OMS pendiente",
    description: "Importador preparado, sin CSV oficiales versionados.",
    area: "pediatric",
    icon: FileCog,
    status: "blocked",
    priority: 40,
    isClinical: true,
    isAdmin: true,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: false,
    allowedContexts: ["admin"],
    blockedReason: "Requiere CSV oficiales y revision clinica antes de importar.",
  },
  {
    id: "sports-profile",
    label: "Perfil deportivo",
    description: "Perfil deportivo y evaluaciones relacionadas.",
    area: "sports",
    route: "/app/pack/sport",
    icon: Dumbbell,
    pack: "sport",
    status: "partial",
    priority: 10,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient", "pack"],
  },
  {
    id: "somatocarta",
    label: "Somatocarta",
    description: "Somatocarta condicionada a datos suficientes.",
    area: "sports",
    route: "/app/somatocarta",
    icon: Trophy,
    pack: "sport",
    status: "active",
    priority: 20,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient", "pack"],
    showInSidebar: true,
  },
  {
    id: "comparator",
    label: "Comparador",
    description: "Comparador visual de indicadores.",
    area: "sports",
    route: "/app/comparator",
    icon: Columns3,
    status: "active",
    priority: 30,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant"],
    showInSidebar: true,
  },
  {
    id: "sports-report",
    label: "Reporte deportivo",
    description: "Reporte deportivo real con secciones de datos insuficientes cuando aplica.",
    area: "sports",
    icon: FileText,
    permission: "reports.export",
    status: "active",
    priority: 40,
    isClinical: true,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
  },
  {
    id: "users-roles",
    label: "Usuarios y roles",
    description: "Gestion de usuarios existentes, roles y memberships.",
    area: "administration",
    route: "/app/users",
    icon: Users,
    permission: "users.manage",
    status: "partial",
    priority: 10,
    isClinical: false,
    isAdmin: true,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: false,
    allowedContexts: ["admin"],
    showInSidebar: true,
    pending: "Invitacion Auth remota pendiente de deploy Edge Function.",
  },
  {
    id: "organization",
    label: "Organizacion",
    description: "Datos institucionales y configuracion del tenant.",
    area: "administration",
    route: "/app/organization",
    icon: Building2,
    permission: "settings.manage",
    status: "active",
    priority: 20,
    isClinical: false,
    isAdmin: true,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: false,
    allowedContexts: ["admin"],
    showInSidebar: true,
  },
  {
    id: "institution-settings",
    label: "Configuracion institucional",
    description: "Branding, packs y configuracion institucional.",
    area: "administration",
    route: "/app/settings",
    icon: Settings,
    permission: "settings.manage",
    status: "active",
    priority: 30,
    isClinical: false,
    isAdmin: true,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: false,
    allowedContexts: ["admin"],
    showInSidebar: true,
  },
  {
    id: "tenant-selector",
    label: "Tenant selector",
    description: "Cambio seguro de organizacion activa.",
    area: "administration",
    route: "/app/tenants",
    icon: Building2,
    status: "active",
    priority: 40,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: false,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["system"],
  },
  {
    id: "audit",
    label: "Auditoria",
    description: "Eventos reales de auditoria institucional.",
    area: "administration",
    route: "/app/audit",
    icon: ShieldAlert,
    permission: "audit.read",
    status: "active",
    priority: 50,
    isClinical: false,
    isAdmin: true,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: false,
    allowedContexts: ["admin"],
    showInSidebar: true,
  },
  {
    id: "reports-center",
    label: "Centro de reportes",
    description: "Reportes clinicos, deportivos, labs y operativos.",
    area: "reports",
    route: "/app/reports",
    icon: FileText,
    permission: "reports.export",
    status: "partial",
    priority: 10,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
    showInSidebar: true,
    pending: "report.exported pendiente en auditoria autenticada.",
  },
  {
    id: "recent-reports",
    label: "Reportes recientes",
    description: "Historial de reportes generados.",
    area: "reports",
    icon: ClipboardCheck,
    permission: "reports.export",
    status: "active",
    priority: 20,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "patient"],
  },
  {
    id: "exports",
    label: "Exportaciones",
    description: "PDF/XLSX reales iniciales con auditoria pendiente de evidencia.",
    area: "reports",
    icon: FileCog,
    permission: "reports.export",
    status: "partial",
    priority: 30,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant"],
    pending: "Confirmar report.exported en /app/audit.",
  },
  {
    id: "modules-center",
    label: "Centro de modulos",
    description: "Mapa local de modulos por area, estado y permiso.",
    area: "system",
    route: "/app/modules",
    icon: Gauge,
    status: "active",
    priority: 10,
    isClinical: false,
    isAdmin: false,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: true,
    allowedContexts: ["tenant", "admin", "system"],
    showInSidebar: true,
  },
  {
    id: "module-settings",
    label: "Configuracion de modulos",
    description: "Vista local de configuracion por area/perfil. Persistencia pendiente.",
    area: "system",
    route: "/app/module-settings",
    icon: Settings,
    permission: "settings.manage",
    status: "partial",
    priority: 20,
    isClinical: false,
    isAdmin: true,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: false,
    allowedContexts: ["admin"],
    showInSidebar: true,
    pending: "Configuracion persistente pendiente de backend tenant-scoped.",
  },
  {
    id: "readiness",
    label: "Readiness",
    description: "Estado local de readiness y bloqueos.",
    area: "system",
    icon: Gauge,
    status: "blocked",
    priority: 30,
    isClinical: false,
    isAdmin: true,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: false,
    allowedContexts: ["admin", "system"],
    blockedReason: "Disponible como scripts/docs, sin pantalla operativa.",
  },
  {
    id: "release-candidate",
    label: "Release candidate",
    description: "Documentacion y artifacts de RC local.",
    area: "system",
    icon: FileCog,
    status: "blocked",
    priority: 40,
    isClinical: false,
    isAdmin: true,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: false,
    allowedContexts: ["admin", "system"],
    blockedReason: "Disponible como docs/artifacts; no se versionan artifacts por defecto.",
  },
  {
    id: "pilot-status",
    label: "Estado del piloto",
    description: "Estado del piloto local y bloqueos externos.",
    area: "system",
    icon: Activity,
    status: "blocked",
    priority: 50,
    isClinical: false,
    isAdmin: true,
    isExperimental: false,
    requiresTenant: true,
    requiresPatient: false,
    comingSoon: false,
    enabledByDefault: false,
    allowedContexts: ["admin", "system"],
    blockedReason: "Fuente documental en docs/README-PILOT.md y docs/pilot-final-status.md.",
  },
];
